stages:
  - deploy

pages:
  stage: deploy
  tags:
    - ubuntu-latest
  script:
    - echo "=== Starting GitLab Pages deployment ==="
    - echo "Current directory contents:"
    - ls -la
    - echo "=== Moving everything to public/ ==="
    - mkdir temp
    - shopt -s dotglob
    - mv * temp/ || true
    - mv temp public
    - echo "=== Cleaning up git files only ==="
    - rm -rf public/.git
    - rm -f public/.gitlab-ci.yml
    - echo "=== Final public/ directory contents ==="
    - ls -la public/
    - echo "=== Deployment complete ==="
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH