export const cards = [{
    name: "Skeletons",
    cost: "1",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1s",
    speed: "Fast",
    img: "/cards/Skeletons.webp",
    emojis: ["\uD83D\uDDE1️", "\uD83D\uDC80", "\uD83D\uDC80", "\uD83D\uDC80"],
    description: "Three fast, very weak melee fighters. Surround your enemies with this pile of bones!"
}, {
    name: "Ice Spirit",
    cost: "1",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "Very Fast",
    img: "/cards/IceSpirit.webp",
    emojis: ["❄️", "\uD83E\uDD76", "\uD83D\uDC7B", "\uD83E\uDD98"],
    description: "Spawns one lively little Ice Spirit to freeze a group of enemies. Stay frosty."
}, {
    name: "Fire Spirit",
    cost: "1",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "Very Fast",
    img: "/cards/FireSpirit.webp",
    emojis: ["\uD83D\uDD25", "\uD83D\uDC7B", "\uD83E\uDD75", "\uD83E\uDD98"],
    description: "The Fire Spirit is on a kamikaze mission to give you a warm hug. It'd be adorable if it wasn't on fire."
}, {
    name: "Electro Spirit",
    cost: "1",
    rarity: "Common",
    type: "Troop",
    release_year: 2020,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "Very Fast",
    img: "/cards/ElectroSpirit.webp",
    emojis: ["⚡", "\uD83D\uDC7B", "\uD83D\uDE35", "\uD83E\uDD98"],
    description: "Jumps on enemies, dealing Area Damage and stunning up to 9 enemy Troops. Locked in an eternal battle with Knight for the best mustache."
}, {
    name: "Heal Spirit",
    cost: "1",
    rarity: "Rare",
    type: "Troop",
    release_year: 2020,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "Very Fast",
    img: "/cards/HealSpirit.webp",
    emojis: ["❤️", "\uD83E\uDE79", "\uD83D\uDC7B", "\uD83E\uDD98"],
    description: "A mischevious Spirit that leaps at enemies, dealing Damage and leaving behind a powerful healing effect that restores Hitpoints to friendly Troops!"
}, {
    name: "Goblins",
    cost: "2",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.1s",
    speed: "Very Fast",
    img: "/cards/Goblins.webp",
    emojis: ["\uD83D\uDC7A", "\uD83D\uDDE1️", "\uD83D\uDCB0", "\uD83D\uDFE2"],
    description: "Four fast, unarmored melee attackers. Small, fast, green and mean!"
}, {
    name: "Bomber",
    cost: "2",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "1.8s",
    speed: "Medium",
    img: "/cards/Bomber.webp",
    emojis: ["\uD83D\uDCA5", "\uD83D\uDCA3", "\uD83D\uDC80", "\uD83E\uDDB4"],
    description: "Small, lightly protected skeleton who throws bombs. Deals area damage that can wipe out a swarm of enemies."
}, {
    name: "Spear Goblins",
    cost: "2",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.7s",
    speed: "Very Fast",
    img: "/cards/SpearGoblins.webp",
    emojis: ["\uD83C\uDFF9", "\uD83C\uDFAF", "\uD83D\uDC7A", "\uD83D\uDCB0"],
    description: "Three unarmored ranged attackers. Who the heck taught these guys to throw spears!? Who thought that was a good idea?!"
}, {
    name: "Ice Golem",
    cost: "2",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "2.5s",
    speed: "Slow",
    img: "/cards/IceGolem.webp",
    emojis: ["❄️", "\uD83E\uDDCA", "\uD83E\uDD76", "\uD83D\uDDFF"],
    description: "He's tough, targets buildings and explodes when destroyed, slowing nearby enemies. Made entirely out of ice... or is he?! Yes."
}, {
    name: "Bats",
    cost: "2",
    rarity: "Common",
    type: "Troop",
    release_year: 2017,
    range: "Melee",
    targets: "Air & Ground",
    hit_speed: "1.3s",
    speed: "Very Fast",
    img: "/cards/Bats.webp",
    emojis: ["\uD83C\uDF83", "\uD83E\uDDDB\uD83C\uDFFB", "\uD83E\uDD87"],
    description: "Spawns a handful of tiny flying creatures. Think of them as sweet, purple... balls of DESTRUCTION!"
}, {
    name: "Wall Breakers",
    cost: "2",
    rarity: "Epic",
    type: "Troop",
    release_year: 2019,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "N/A",
    speed: "Very Fast",
    img: "/cards/WallBreakers.webp",
    emojis: ["\uD83D\uDCA3", "\uD83C\uDFC3", "\uD83D\uDCA5", "\uD83D\uDC80"],
    description: "A daring duo of dangerous dive bombers. Nothing warms a Wall Breaker's cold and undead heart like blowing up buildings."
}, {
    name: "Suspicious Bush",
    cost: "2",
    rarity: "Rare",
    type: "Troop",
    release_year: 2024,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "1.4s",
    speed: "Medium",
    img: "/cards/SuspiciousBush.webp",
    emojis: ["\uD83C\uDF33", "\uD83C\uDF43", "\uD83D\uDC7A", "\uD83D\uDC7A"],
    description: "This invisible bush skulks towards the nearest building. Sus. If Suspicious Bush reaches its target or gets destroyed by a spell, it surprises the enemy with Bush Goblins!"
}, {
    name: "Berserker",
    cost: "2",
    rarity: "Common",
    type: "Troop",
    release_year: 2025,
    range: "Melee",
    targets: "Ground",
    hit_speed: "0.5s",
    speed: "Fast",
    img: "/cards/Berserker.webp",
    emojis: ["\uD83D\uDC76", "\uD83D\uDE08", "\uD83E\uDE93", "\uD83E\uDE93"],
    description: "It's surprising how often she needs her axes sharpened, but then again, if you liked hitting things as fast as her, so would you."
}, {
    name: "Knight",
    cost: "3",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.2s",
    speed: "Medium",
    img: "/cards/Knight.webp",
    emojis: ["\uD83E\uDD3A", "⚔️", "⚜️", "\uD83C\uDFC7"],
    description: "A tough melee fighter. The Barbarian's handsome, cultured cousin. Rumor has it that he was knighted based on the sheer awesomeness of his mustache alone."
}, {
    name: "Archers",
    cost: "3",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "0.9s",
    speed: "Medium",
    img: "/cards/Archers.webp",
    emojis: ["\uD83D\uDC85\uD83C\uDFFB", "\uD83D\uDC6F", "\uD83C\uDFF9", "\uD83C\uDFAF"],
    description: "A pair of lightly armored ranged attackers. They'll help you take down ground and air units, but you're on your own with hair coloring advice."
}, {
    name: "Minions",
    cost: "3",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.1s",
    speed: "Fast",
    img: "/cards/Minions.webp",
    emojis: ["\uD83D\uDC7E", "\uD83D\uDC7E", "\uD83D\uDC7E"],
    description: "Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!"
}, {
    name: "Skeleton Army",
    cost: "3",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1s",
    speed: "Fast",
    img: "/cards/SkeletonArmy.webp",
    emojis: ["\uD83D\uDC80", "\uD83D\uDC80", "\uD83D\uDC80", "⚔️"],
    description: "Spawns an army of Skeletons. Meet Larry and his friends Harry, Terry, Gerry, Mary, etc."
}, {
    name: "Ice Wizard",
    cost: "3",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.7s",
    speed: "Medium",
    img: "/cards/IceWizard.webp",
    emojis: ["\uD83E\uDD76", "❄️", "\uD83E\uDDD9‍♂️"],
    description: "This chill caster throws ice shards that slow down enemies' movement and attack speed. Despite being freezing cold, he has a handlebar mustache that's too hot for TV."
}, {
    name: "Guards",
    cost: "3",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1s",
    speed: "Fast",
    img: "/cards/Guards.webp",
    emojis: ["\uD83D\uDEE1️", "\uD83D\uDDE1️", "\uD83D\uDC80", "⚔️"],
    description: "Three ruthless bone brothers with shields. Knock off their shields and all that's left are three ruthless bone brothers."
}, {
    name: "Princess",
    cost: "3",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "3s",
    speed: "Medium",
    img: "/cards/Princess.webp",
    emojis: ["\uD83D\uDC51", "\uD83C\uDFF9", "\uD83C\uDFAF", "\uD83D\uDC78"],
    description: "This stunning Princess shoots flaming arrows from long range. If you're feeling warm feelings towards her, it's probably because you're on fire."
}, {
    name: "Miner",
    cost: "3",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.3s",
    speed: "Fast",
    img: "/cards/Miner.webp",
    emojis: ["\uD83D\uDD73️", "⛏️", "\uD83D\uDC77"],
    description: "The Miner can burrow his way underground and appear anywhere in the Arena. It's not magic, it's a shovel. A shovel that deals reduced damage to Crown Towers."
}, {
    name: "Mega Minion",
    cost: "3",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Air & Ground",
    hit_speed: "1.6s",
    speed: "Medium",
    img: "/cards/MegaMinion.webp",
    emojis: ["\uD83E\uDD16", "\uD83D\uDCAA", "\uD83D\uDC7E", "\uD83D\uDC09"],
    description: "Flying, armored and powerful. What could be its weakness?! Cupcakes."
}, {
    name: "Dart Goblin",
    cost: "3",
    rarity: "Rare",
    type: "Troop",
    release_year: 2017,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "0.8s",
    speed: "Very Fast",
    img: "/cards/DartGoblin.webp",
    emojis: ["\uD83C\uDFAF", "\uD83C\uDF2C️", "\uD83C\uDFAD", "\uD83D\uDC7A"],
    description: "Runs fast, shoots far and chews gum. How does he blow darts with a mouth full of Double Trouble gum? Years of didgeridoo lessons."
}, {
    name: "Goblin Gang",
    cost: "3",
    rarity: "Common",
    type: "Troop",
    release_year: 2017,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.1s",
    speed: "Very Fast",
    img: "/cards/GoblinGang.webp",
    emojis: ["\uD83D\uDC7A", "\uD83D\uDDE1️", "\uD83D\uDC7A", "\uD83C\uDFF9"],
    description: "Spawns Six Goblins - three with knives, three with spears - at a discounted Elixir cost. It's like a Goblin Value Pack!"
}, {
    name: "Bandit",
    cost: "3",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2017,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1s",
    speed: "Fast",
    img: "/cards/Bandit.webp",
    emojis: ["\uD83C\uDFC3‍♀️", "\uD83E\uDDB9‍♂️", "\uD83C\uDFCF"],
    description: "The Bandit dashes to her target and delivers an extra big hit! While dashing, she can't be touched. The mask keeps her identity safe, and gives her bonus cool points!"
}, {
    name: "Royal Ghost",
    cost: "3",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2018,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.8s",
    speed: "Fast",
    img: "/cards/RoyalGhost.webp",
    emojis: ["\uD83E\uDD34", "\uD83D\uDE34", "\uD83D\uDDE1️", "\uD83D\uDC7B"],
    description: "He drifts invisibly through the Arena until he's startled by an enemy... then he attacks! Then he's invisible again! Zzzz."
}, {
    name: "Skeleton Barrel",
    cost: "3",
    rarity: "Common",
    type: "Troop",
    release_year: 2017,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "N/A",
    speed: "Fast",
    img: "/cards/SkeletonBarrel.webp",
    emojis: ["\uD83D\uDEE2️", "\uD83D\uDC80", "\uD83C\uDF88"],
    description: "It's a Skeleton party in the sky, until all the balloons pop... then it's a Skeleton party on the ground!"
}, {
    name: "Fisherman",
    cost: "3",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2019,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.3s",
    speed: "Medium",
    img: "/cards/Fisherman.webp",
    emojis: ["\uD83E\uDDD4", "\uD83E\uDDE2", "⚓", "\uD83C\uDFA3"],
    description: "His Ranged Attack can pull enemies towards him, and pull himself to enemy buildings. He's also mastered the ancient art of 'Fish Slapping'."
}, {
    name: "Firecracker",
    cost: "3",
    rarity: "Common",
    type: "Troop",
    release_year: 2020,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "3s",
    speed: "Fast",
    img: "/cards/Firecracker.webp",
    emojis: ["\uD83E\uDDE8", "\uD83C\uDF89", "\uD83C\uDF86", "\uD83D\uDC69\uD83C\uDFFB"],
    description: "Shoots a firework that explodes on impact, damaging the target and showering anything behind it with sparks. This is what happens when Archers get bored!"
}, {
    name: "Elixir Golem",
    cost: "3",
    rarity: "Rare",
    type: "Troop",
    release_year: 2019,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "1.3s",
    speed: "Slow",
    img: "/cards/ElixirGolem.webp",
    emojis: ["\uD83E\uDDEA", "⚗️", "\uD83D\uDDFF"],
    description: "Splits into two Elixir Golemites when destroyed, which split into two sentient Blobs when defeated. Each part of the Elixir Golem gives your opponent some Elixir when destroyed!"
}, {
    name: "Little Prince",
    cost: "3",
    rarity: "Champion",
    type: "Troop",
    release_year: 2023,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.2s",
    speed: "Medium",
    img: "/cards/LittlePrince.webp",
    emojis: ["\uD83D\uDC76", "\uD83E\uDD34\uD83C\uDFFB", "\uD83E\uDD3A"],
    description: "Who let their nephew into the Arena?! This mischievous Royal gains Hit Speed when firing, as long as he stands still! He may look weak, but he's always being watched over from afar..."
}, {
    name: "Goblin Machine",
    cost: "5",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2024,
    range: "Melee",
    targets: "Air & Ground",
    hit_speed: "0.9s",
    speed: "Medium",
    img: "/cards/GoblinMachine.webp",
    emojis: ["\uD83D\uDC76\uD83C\uDFFB", "\uD83E\uDD16", "\uD83D\uDC7A", "\uD83D\uDE80"],
    description: "Goblin Machine has two arms for melee and one big rocket for faraway targets. Who let a baby drive this thing?"
}, {
    name: "Valkyrie",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.5s",
    speed: "Medium",
    img: "/cards/Valkyrie.webp",
    emojis: ["\uD83D\uDC69", "\uD83D\uDCAA", "\uD83D\uDD04", "\uD83E\uDE93"],
    description: "Tough melee fighter, deals area damage around her. Swarm or horde, no problem! She can take them all out with a few spins."
}, {
    name: "Musketeer",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1s",
    speed: "Medium",
    img: "/cards/Musketeer.webp",
    emojis: ["\uD83C\uDF96️", "\uD83C\uDFAF", "\uD83D\uDC82\uD83C\uDFFB", "\uD83D\uDD2B"],
    description: "Don't be fooled by her delicately coiffed hair, the Musketeer is a mean shot with her trusty boomstick."
}, {
    name: "Baby Dragon",
    cost: "4",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.5s",
    speed: "Fast",
    img: "/cards/BabyDragon.webp",
    emojis: ["\uD83D\uDD25", "\uD83D\uDC09", "\uD83D\uDC76"],
    description: "Burps fireballs from the sky that deal area damage. Baby dragons hatch cute, hungry and ready for a barbeque."
}, {
    name: "Mini P.E.K.K.A",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.6s",
    speed: "Fast",
    img: "/cards/MiniPekka.webp",
    emojis: ["\uD83D\uDC76", "\uD83E\uDD16", "\uD83E\uDDBE"],
    description: "The Arena is a certified butterfly-free zone. No distractions for P.E.K.K.A, only destruction."
}, {
    name: "Hog Rider",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "1.6s",
    speed: "Very Fast",
    img: "/cards/HogRider.webp",
    emojis: ["\uD83C\uDFC7", "\uD83D\uDD28", "\uD83D\uDC17", "\uD83D\uDC68\uD83C\uDFFF‍\uD83E\uDDB2"],
    description: 'Fast melee troop that targets buildings and can jump over the river. He followed the echoing call of "Hog Riderrrrr" all the way through the Arena doors.'
}, {
    name: "Dark Prince",
    cost: "4",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.3s",
    speed: "Medium",
    img: "/cards/DarkPrince.webp",
    emojis: ["⚫", "\uD83D\uDEE1️", "\uD83C\uDFC7", "\uD83E\uDD34\uD83C\uDFFB"],
    description: "The Dark Prince deals area damage and lets his spiked club do the talking for him - because when he does talk, it sounds like he has a bucket on his head."
}, {
    name: "Lumberjack",
    cost: "4",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "0.8s",
    speed: "Very Fast",
    img: "/cards/Lumberjack.webp",
    emojis: ["\uD83C\uDF32", "\uD83E\uDDD4", "\uD83E\uDE93", "\uD83C\uDF7A"],
    description: "He chops trees by day and hunts The Log by night. His bottle of Rage spills everywhere when he's defeated."
}, {
    name: "Battle Ram",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2017,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "N/A",
    speed: "Medium",
    img: "/cards/BattleRam.webp",
    emojis: ["\uD83C\uDFC3", "\uD83D\uDCA5", "\uD83E\uDD3A", "\uD83C\uDF32"],
    description: "Two Barbarians holding a big log charge at the nearest building, dealing significant damage if they connect; then they go to town with their swords!"
}, {
    name: "Inferno Dragon",
    cost: "4",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "0.4s",
    speed: "Medium",
    img: "/cards/InfernoDragon.webp",
    emojis: ["\uD83D\uDD25", "\uD83C\uDF0B", "\uD83D\uDC09"],
    description: "Shoots a focused beam of fire that increases in damage over time. Wears a helmet because flying can be dangerous."
}, {
    name: "Electro Wizard",
    cost: "4",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.8s",
    speed: "Fast",
    img: "/cards/ElectroWizard.webp",
    emojis: ["⚡", "⚡", "\uD83D\uDC68\uD83C\uDFFB", "\uD83E\uDDD9‍♂️"],
    description: 'He lands with a "POW!", stuns nearby enemies and shoots lightning with both hands! What a show off.'
}, {
    name: "Hunter",
    cost: "4",
    rarity: "Epic",
    type: "Troop",
    release_year: 2017,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "2.2s",
    speed: "Medium",
    img: "/cards/Hunter.webp",
    emojis: ["\uD83D\uDD78️", "\uD83D\uDD2B", "\uD83E\uDDE2", "\uD83E\uDDD4\uD83C\uDFFB"],
    description: "He deals BIG damage up close - not so much at range. What he lacks in accuracy, he makes up for with his impressively bushy eyebrows."
}, {
    name: "Night Witch",
    cost: "4",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2017,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.5s",
    speed: "Medium",
    img: "/cards/NightWitch.webp",
    emojis: ["\uD83E\uDDD9‍♀️", "\uD83E\uDE93", "✨", "\uD83E\uDD87"],
    description: "Summons Bats to do her bidding! If you get too close, she's not afraid of pitching in with her mean-looking battle staff."
}, {
    name: "Zappies",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2017,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "2.1s",
    speed: "Medium",
    img: "/cards/Zappies.webp",
    emojis: ["\uD83E\uDD16", "\uD83E\uDD16", "\uD83E\uDD16", "⚡"],
    description: "Spawns a pack of miniature Zap machines. Who controls them...? Only the Master Builder knows."
}, {
    name: "Flying Machine",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2017,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.1s",
    speed: "Fast",
    img: "/cards/FlyingMachine.webp",
    emojis: ["✈️", "\uD83D\uDD2B", "\uD83E\uDD16", "⚙️"],
    description: "The Master Builder has sent his first contraption to the Arena! It's a fast and fun flying machine, but fragile!"
}, {
    name: "Magic Archer",
    cost: "4",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2018,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.1s",
    speed: "Medium",
    img: "/cards/MagicArcher.webp",
    emojis: ["\uD83C\uDFF9", "✨", "\uD83E\uDDDD"],
    description: "Not quite a Wizard, nor an Archer - he shoots a magic arrow that passes through and damages all enemies in its path. It's not a trick, it's magic!"
}, {
    name: "Mighty Miner",
    cost: "4",
    rarity: "Champion",
    type: "Troop",
    release_year: 2022,
    range: "Melee",
    targets: "Ground",
    hit_speed: "0.4s",
    speed: "Medium",
    img: "/cards/MightyMiner.webp",
    emojis: ["\uD83D\uDCA3", "⛏️", "\uD83D\uDC77", "\uD83D\uDCAA"],
    description: "Walk softly... and carry a big drill! This Champion deals increasing Damage to his target and can switch lanes to escape combat or change attack plans. This makes him not only the mightiest, but also the sneakiest Miner in the Arena."
}, {
    name: "Battle Healer",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2020,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.5s",
    speed: "Medium",
    img: "/cards/BattleHealer.webp",
    emojis: ["⚔️", "❤️", "\uD83D\uDC7C"],
    description: "With each attack, she unleashes a powerful healing aura that restores Hitpoints to herself and friendly Troops."
}, {
    name: "Skeleton King",
    cost: "4",
    rarity: "Champion",
    type: "Troop",
    release_year: 2021,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.6s",
    speed: "Medium",
    img: "/cards/SkeletonKing.webp",
    emojis: ["\uD83E\uDD3A", "\uD83D\uDC80", "⚔️", "\uD83E\uDD34\uD83C\uDFFB"],
    description: "The King of the undead himself. He sometimes feels lonely (could be due to his non flattering features) and will summon friends to join him in the battle even after death. Tough guys have feelings too!"
}, {
    name: "Golden Knight",
    cost: "4",
    rarity: "Champion",
    type: "Troop",
    release_year: 2021,
    range: "Melee",
    targets: "Ground",
    hit_speed: "0.9s",
    speed: "Medium",
    img: "/cards/GoldenKnight.webp",
    emojis: ["\uD83E\uDD3A", "⚜️", "\uD83E\uDD34\uD83C\uDFFB", "\uD83E\uDDC8"],
    description: "A warrior with luxurious hair and outstanding flexibility. Demonstrates his aerobics skills on demand."
}, {
    name: "Skeleton Dragons",
    cost: "4",
    rarity: "Common",
    type: "Troop",
    release_year: 2020,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.9s",
    speed: "Fast",
    img: "/cards/SkeletonDragons.webp",
    emojis: ["\uD83D\uDC80", "\uD83D\uDD25", "\uD83D\uDC09", "\uD83D\uDC09"],
    description: "This pair of skeletal scorchers deal Area Damage and fly above the Arena. They also play a mean rib cage xylophone duet."
}, {
    name: "Mother Witch",
    cost: "4",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2020,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.1s",
    speed: "Medium",
    img: "/cards/MotherWitch.webp",
    emojis: ["\uD83D\uDC37", "✨", "\uD83E\uDD31\uD83C\uDFFB", "\uD83E\uDDD9\uD83C\uDFFB‍♀️"],
    description: "Places a curse on enemy troops with each attack. When a cursed troop is destroyed, it turns into a building-targeting Hog that fights alongside the Mother Witch. She also bakes great cookies."
}, {
    name: "Phoenix",
    cost: "4",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2022,
    range: "Melee",
    targets: "Air & Ground",
    hit_speed: "1s",
    speed: "Medium",
    img: "/cards/Phoenix.webp",
    emojis: ["\uD83D\uDD25", "\uD83D\uDC23", "\uD83D\uDC26"],
    description: "This mystical creature will be reborn as an egg when destroyed. If it hatches, it returns to the fight! What an egg-cellent ability. Being born again is tiring, so a hatched Phoenix will have slightly less Hitpoints and Damage (80% of its total)."
}, {
    name: "Goblin Demolisher",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2024,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "1.1s",
    speed: "Medium",
    img: "/cards/GoblinDemolisher.webp",
    emojis: ["\uD83D\uDC7A", "\uD83C\uDFC3", "\uD83E\uDDE8", "\uD83D\uDCA5"],
    description: "Boom goes dynamite! Goblin Demolisher deals area damage and explodes on death. At low health, he charges towards the nearest building."
}, {
    name: "Rune Giant",
    cost: "4",
    rarity: "Epic",
    type: "Troop",
    release_year: 2025,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "1.5s",
    speed: "Medium",
    img: "/cards/RuneGiant.webp",
    emojis: ["\uD83D\uDDFF", "\uD83D\uDCAA", "\uD83D\uDD28", "➰"],
    description: "Need your weapons sharpened? You've come to the right place. Rune Giant enchants Troops closest to her, haing them deal Bonus Damage every third attack. Only two Troops can be enchanted at once."
}, {
    name: "Giant",
    cost: "5",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "1.5s",
    speed: "Slow",
    img: "/cards/Giant.webp",
    emojis: ["\uD83D\uDCAA", "\uD83D\uDDFF", "\uD83D\uDC4A", "\uD83D\uDC68\uD83C\uDFFB‍\uD83E\uDDB0"],
    description: "Slow but durable, only attacks buildings. A real one-man wrecking crew!"
}, {
    name: "Balloon",
    cost: "5",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "2s",
    speed: "Medium",
    img: "/cards/Balloon.webp",
    emojis: ["\uD83D\uDCA3", "\uD83D\uDCA5", "\uD83D\uDC80", "\uD83C\uDF88"],
    description: "As pretty as they are, you won't want a parade of THESE balloons showing up on the horizon. Drops powerful bombs and when shot down, crashes dealing area damage."
}, {
    name: "Witch",
    cost: "5",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.1s",
    speed: "Medium",
    img: "/cards/Witch.webp",
    emojis: ["\uD83D\uDC80", "✨", "\uD83D\uDD2E", "\uD83E\uDDD9\uD83C\uDFFB‍♀️"],
    description: "Summons Skeletons, shoots destructo beams, has glowing pink eyes that unfortunately don't shoot lasers."
}, {
    name: "Barbarians",
    cost: "5",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.4s",
    speed: "Medium",
    img: "/cards/Barbarians.webp",
    emojis: ["⚔️", "\uD83E\uDD3A", "\uD83E\uDDD4\uD83C\uDFFC", "\uD83E\uDDD4\uD83C\uDFFC"],
    description: "A horde of melee attackers with mean mustaches and even meaner tempers."
}, {
    name: "Prince",
    cost: "5",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.4s",
    speed: "Medium",
    img: "/cards/Prince.webp",
    emojis: ["\uD83C\uDF62", "\uD83C\uDFC7", "\uD83E\uDD34\uD83C\uDFFB"],
    description: "Don't let the little pony fool you. Once the Prince gets a running start, you WILL be trampled. Deals double damage once he gets charging."
}, {
    name: "Wizard",
    cost: "5",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.4s",
    speed: "Medium",
    img: "/cards/Wizard.webp",
    emojis: ["\uD83D\uDD25", "✨", "\uD83E\uDDD9"],
    description: "The most awesome man to ever set foot in the Arena, the Wizard will blow you away with his handsomeness... and/or fireballs."
}, {
    name: "Minion Horde",
    cost: "5",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.1s",
    speed: "Fast",
    img: "/cards/MinionHorde.webp",
    emojis: ["\uD83D\uDC7E", "\uD83D\uDC7E", "\uD83D\uDC7E", "\uD83D\uDC7E"],
    description: "Six fast, unarmored flying attackers. Three's a crowd, six is a horde!"
}, {
    name: "Bowler",
    cost: "5",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "2.5s",
    speed: "Slow",
    img: "/cards/Bowler.webp",
    emojis: ["\uD83D\uDDFF", "\uD83D\uDC68‍\uD83E\uDDB2", "\uD83D\uDFE3", "\uD83C\uDFB3"],
    description: "This big blue dude digs the simple things in life - Dark Elixir drinks and throwing rocks. His massive boulders roll through their target, hitting everything behind for a strike!"
}, {
    name: "Executioner",
    cost: "5",
    rarity: "Epic",
    type: "Troop",
    release_year: 2017,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "2.4s",
    speed: "Medium",
    img: "/cards/Executioner.webp",
    emojis: ["\uD83E\uDE93", "\uD83C\uDFAF", "\uD83D\uDD04", "\uD83E\uDDB9‍♂️"],
    description: "He throws his axe like a boomerang, striking all enemies on the way out AND back. It's a miracle he doesn't lose an arm."
}, {
    name: "Ram Rider",
    cost: "5",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2018,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "1.8s",
    speed: "Medium",
    img: "/cards/RamRider.webp",
    emojis: ["\uD83E\uDD20", "\uD83C\uDFC7", "\uD83D\uDC10"],
    description: "Together they charge through the Arena; snaring enemies, knocking down towers... and chewing grass!?"
}, {
    name: "Rascals",
    cost: "5",
    rarity: "Common",
    type: "Troop",
    release_year: 2018,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1s",
    speed: "Medium",
    img: "/cards/Rascals.webp",
    emojis: ["\uD83D\uDE08", "\uD83C\uDFF9", "\uD83D\uDC67\uD83C\uDFFB", "\uD83E\uDDD1\uD83C\uDFFB"],
    description: "Spawns a mischievous trio of Rascals! The boy takes the lead, while the girls pelt enemies from behind... with slingshots full of Double Trouble Gum!"
}, {
    name: "Cannon Cart",
    cost: "5",
    rarity: "Epic",
    type: "Troop",
    release_year: 2017,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "1s",
    speed: "Medium",
    img: "/cards/CannonCart.webp",
    emojis: ["\uD83D\uDCA3", "\uD83D\uDD2B", "⚙️", "\uD83D\uDED2"],
    description: "A Cannon on wheels?! Bet they won't see that coming! At low health, it becomes a Cannon not on wheels."
}, {
    name: "Royal Hogs",
    cost: "5",
    rarity: "Rare",
    type: "Troop",
    release_year: 2018,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "1.2s",
    speed: "Very Fast",
    img: "/cards/RoyalHogs.webp",
    emojis: ["\uD83D\uDC51", "\uD83D\uDC16", "\uD83D\uDC16", "\uD83D\uDC16"],
    description: "The King's personal pets are loose! They love to chomp on apples and towers alike - who let the hogs out?!"
}, {
    name: "Electro Dragon",
    cost: "5",
    rarity: "Epic",
    type: "Troop",
    release_year: 2018,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "2.1s",
    speed: "Medium",
    img: "/cards/ElectroDragon.webp",
    emojis: ["⚡", "⛓️", "\uD83D\uDC09"],
    description: "Spits out bolts of electricity hitting up to three targets. Suffers from middle child syndrome to boot."
}, {
    name: "Archer Queen",
    cost: "5",
    rarity: "Champion",
    type: "Troop",
    release_year: 2021,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.2s",
    speed: "Medium",
    img: "/cards/ArcherQueen.webp",
    emojis: ["\uD83C\uDFF9", "\uD83C\uDFAF", "\uD83D\uDC51", "\uD83D\uDC78\uD83C\uDFFB"],
    description: "She is fast, deadly and hard to catch. Beware of her crossbow bolts and try not to blink - you might miss her!"
}, {
    name: "Monk",
    cost: "5",
    rarity: "Champion",
    type: "Troop",
    release_year: 2022,
    range: "Melee",
    targets: "Ground",
    hit_speed: "0.9s",
    speed: "Medium",
    img: "/cards/Monk.webp",
    emojis: ["☯️", "\uD83E\uDDD8", "\uD83D\uDE4F", "\uD83D\uDC68\uD83C\uDFFB‍\uD83E\uDDB3"],
    description: "Monk has spent many isolated years perfecting a new style of combat. He fires off a 3-hit combo, with the last blow dealing extra Damage and pushing enemies back!"
}, {
    name: "Goblinstein",
    cost: "5",
    rarity: "Champion",
    type: "Troop",
    release_year: 2024,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.8s",
    speed: "Medium",
    img: "/cards/Goblinstein.webp",
    emojis: ["\uD83D\uDC68‍⚕", "⚡", "\uD83E\uDDDF‍♂️"],
    description: "It's ALIVE! Monster lumbers towards enemy buildings while Doctor waits to spring the trap. At the press of a button, Doctor electrifies the link between himself and Monster, frying nearby enemies!"
}, {
    name: "Giant Skeleton",
    cost: "6",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.4s",
    speed: "Medium",
    img: "/cards/GiantSkeleton.webp",
    emojis: ["\uD83D\uDCA3", "\uD83D\uDC80", "\uD83D\uDCA5", "\uD83D\uDDFF"],
    description: "The bigger the skeleton, the bigger the bomb. Carries a bomb that blows up when the Giant Skeleton dies."
}, {
    name: "Royal Giant",
    cost: "6",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Buildings",
    hit_speed: "1.7s",
    speed: "Slow",
    img: "/cards/RoyalGiant.webp",
    emojis: ["\uD83D\uDDFF", "\uD83D\uDC51", "\uD83D\uDCAA", "\uD83D\uDD2B"],
    description: "Destroying enemy buildings with his massive cannon is his job; making a raggedy blond beard look good is his passion."
}, {
    name: "Sparky",
    cost: "6",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "4s",
    speed: "Slow",
    img: "/cards/Sparky.webp",
    emojis: ["⚡", "⚙️", "\uD83D\uDED2"],
    description: "Sparky slowly charges up, then unloads MASSIVE area damage. Overkill isn't in her vocabulary."
}, {
    name: "Elite Barbarians",
    cost: "6",
    rarity: "Common",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.4s",
    speed: "Fast",
    img: "/cards/EliteBarbarians.webp",
    emojis: ["\uD83E\uDD3A", "\uD83E\uDD3A", "\uD83D\uDCAA", "\uD83C\uDF96️"],
    description: "Spawns a pair of leveled up Barbarians. They're like regular Barbarians, only harder, better, faster and stronger."
}, {
    name: "Goblin Giant",
    cost: "6",
    rarity: "Epic",
    type: "Troop",
    release_year: 2018,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "1.5s",
    speed: "Medium",
    img: "/cards/GoblinGiant.webp",
    emojis: ["\uD83D\uDC7A", "\uD83D\uDCAA", "\uD83D\uDDFF"],
    description: "This jolly green Goblin Giant stomps towards enemy buildings. He carries two Spear Goblins everywhere he goes. It's a weird but functional arrangement."
}, {
    name: "Boss Bandit",
    cost: "6",
    rarity: "Champion",
    type: "Troop",
    release_year: 2025,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.2s",
    speed: "Fast",
    img: "/cards/BossBandit.webp",
    emojis: ["\uD83C\uDFC3‍♀️", "\uD83E\uDDB9‍♂️", "\uD83C\uDFCF", "\uD83D\uDC69\uD83C\uDFFB‍\uD83D\uDCBC"],
    description: "The boss of the Forest Gang finally shows her face...kind of. Boss Bandit dashes to her targets and is invulnerable while dashing. When things get tough, her pair of grenades are at the ready."
}, {
    name: "P.E.K.K.A",
    cost: "7",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.8s",
    speed: "Slow",
    img: "/cards/Pekka.webp",
    emojis: ["\uD83E\uDD16", "\uD83E\uDDBE", "⚔️"],
    description: "A heavily armored, slow melee fighter. Swings from the hip, but packs a huge punch."
}, {
    name: "Lava Hound",
    cost: "7",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Buildings",
    hit_speed: "1.3s",
    speed: "Slow",
    img: "/cards/LavaHound.webp",
    emojis: ["✈️", "\uD83C\uDF0B", "\uD83D\uDCA5", "\uD83D\uDC09"],
    description: "The Lava Hound is a majestic flying beast that attacks buildings. The Lava Pups are less majestic angry babies that attack anything."
}, {
    name: "Royal Recruits",
    cost: "7",
    rarity: "Common",
    type: "Troop",
    release_year: 2018,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.3s",
    speed: "Medium",
    img: "/cards/RoyalRecruits.webp",
    emojis: ["\uD83C\uDFF0", "\uD83D\uDEE1️", "\uD83D\uDC82", "\uD83D\uDC51"],
    description: "Deploys a line of recruits armed with spears, shields and wooden buckets. They dream of ponies and one day wearing metal buckets."
}, {
    name: "Mega Knight",
    cost: "7",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2017,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.7s",
    speed: "Medium",
    img: "/cards/MegaKnight.webp",
    emojis: ["\uD83D\uDCAA", "\uD83E\uDD3A", "⚔️", "⚜️"],
    description: "He lands with the force of 1,000 mustaches, then jumps from one foe to the next dealing huge area damage. Stand aside!"
}, {
    name: "Electro Giant",
    cost: "7",
    rarity: "Epic",
    type: "Troop",
    release_year: 2020,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "2.1s",
    speed: "Slow",
    img: "/cards/ElectroGiant.webp",
    emojis: ["⚡", "\uD83D\uDCAA", "\uD83D\uDDFF", "\uD83D\uDC68\uD83C\uDFFC‍\uD83E\uDDB0"],
    description: "He channels electricity through his Zap Pack, a unique device that stuns and damages any troop attacking him within its range. Don't tell him that his finger guns aren't real! He'll zap you."
}, {
    name: "Golem",
    cost: "8",
    rarity: "Epic",
    type: "Troop",
    release_year: 2016,
    range: "Melee",
    targets: "Buildings",
    hit_speed: "2.5s",
    speed: "Slow",
    img: "/cards/Golem.webp",
    emojis: ["\uD83C\uDFD4️", "\uD83D\uDCAA", "\uD83D\uDDFF"],
    description: "Slow but durable, only attacks buildings. When destroyed, explosively splits into two Golemites and deals area damage!"
}, {
    name: "Three Musketeers",
    cost: "9",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1s",
    speed: "Medium",
    img: "/cards/ThreeMusketeers.webp",
    emojis: ["\uD83D\uDC82\uD83C\uDFFB", "\uD83D\uDC82\uD83C\uDFFB", "\uD83D\uDC82\uD83C\uDFFB", "\uD83D\uDD2B"],
    description: "Trio of powerful, independent markswomen, fighting for justice and honor. Disrespecting them would not be just a mistake, it would be a cardinal sin!"
}, {
    name: "Cannon",
    cost: "3",
    rarity: "Common",
    type: "Building",
    release_year: 2016,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "0.9s",
    speed: "N/A",
    img: "/cards/Cannon.webp",
    emojis: ["\uD83D\uDCA3", "\uD83D\uDD2B", "⚒️", "\uD83C\uDFDA️"],
    description: "Defensive building. Shoots cannonballs with deadly effect, but cannot target flying troops."
}, {
    name: "Tombstone",
    cost: "3",
    rarity: "Rare",
    type: "Building",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1s",
    speed: "Fast",
    img: "/cards/Tombstone.webp",
    emojis: ["\uD83C\uDFDA️", "\uD83D\uDC80", "⚰️"],
    description: "Building that periodically spawns Skeletons to fight the enemy... and when destroyed, spawns 4 more Skeletons! Creepy."
}, {
    name: "Mortar",
    cost: "4",
    rarity: "Common",
    type: "Building",
    release_year: 2016,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "5s",
    speed: "N/A",
    img: "/cards/Mortar.webp",
    emojis: ["\uD83C\uDFDA️", "\uD83C\uDFAF", "\uD83D\uDCA3", "\uD83C\uDFF9"],
    description: "Defensive building with a long range. Shoots big boulders that deal area damage, but cannot hit targets that get very close!"
}, {
    name: "Bomb Tower",
    cost: "4",
    rarity: "Rare",
    type: "Building",
    release_year: 2016,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "1.6s",
    speed: "N/A",
    img: "/cards/BombTower.webp",
    emojis: ["\uD83C\uDFDA️", "\uD83E\uDD3E", "\uD83D\uDC80", "\uD83D\uDCA3"],
    description: "Defensive building that houses a Bomber. Deals area damage to anything dumb enough to stand near it."
}, {
    name: "Tesla",
    cost: "4",
    rarity: "Common",
    type: "Building",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.2s",
    speed: "N/A",
    img: "/cards/Tesla.webp",
    emojis: ["\uD83D\uDE48", "⚡", "\uD83D\uDE48", "\uD83D\uDDFC"],
    description: "Defensive building. Whenever it's not zapping the enemy, the power of Electrickery is best kept grounded."
}, {
    name: "Furnace",
    cost: "4",
    rarity: "Rare",
    type: "Troop",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.8s",
    speed: "Slow",
    img: "/cards/Furnace.webp",
    emojis: ["\uD83C\uDF0B", "\uD83D\uDD25", "\uD83D\uDC7B", "\uD83C\uDFED"],
    description: "Spawns one Fire Spirit at a time while dealing damage with its special cauldron brew. It also makes great brick-oven pancakes."
}, {
    name: "Goblin Cage",
    cost: "4",
    rarity: "Rare",
    type: "Building",
    release_year: 2019,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.1s",
    speed: "Fast",
    img: "/cards/GoblinCage.webp",
    emojis: ["\uD83C\uDFDA️", "\uD83D\uDC7A", "\uD83D\uDD12", "⛓️"],
    description: "When the Goblin Cage is destroyed, a Goblin Brawler is unleashed into the Arena! Goblin Brawler always skips leg day."
}, {
    name: "Goblin Drill",
    cost: "4",
    rarity: "Epic",
    type: "Building",
    release_year: 2021,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.1s",
    speed: "Very Fast",
    img: "/cards/GoblinDrill.webp",
    emojis: ["\uD83D\uDC7A", "\uD83D\uDEE0️", "⛏️", "\uD83C\uDFDA️"],
    description: "Building capable of burrowing underground and appearing anywhere in the Arena. Spawns Goblins one at a time until destroyed. Then spawns a few more, to make sure everything nearby has been properly stabbed."
}, {
    name: "Goblin Hut",
    cost: "4",
    rarity: "Rare",
    type: "Building",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.7s",
    speed: "Very Fast",
    img: "/cards/GoblinHut.webp",
    emojis: ["\uD83C\uDFDA️", "✨", "\uD83D\uDC7A", "\uD83D\uDC7A"],
    description: "Defensive building that spawns Spear Goblins when enemies are in range. Don't look inside... you don't want to see how they're made."
}, {
    name: "Inferno Tower",
    cost: "5",
    rarity: "Rare",
    type: "Building",
    release_year: 2016,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "0.4s",
    speed: "N/A",
    img: "/cards/InfernoTower.webp",
    emojis: ["\uD83C\uDFDA️", "\uD83C\uDFAF", "☄️", "\uD83C\uDF0B"],
    description: "Defensive building, roasts targets for damage that increases over time. Burns through even the biggest and toughest enemies!"
}, {
    name: "Elixir Collector",
    cost: "6",
    rarity: "Rare",
    type: "Building",
    release_year: 2016,
    range: "N/A",
    targets: "N/A",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/ElixirCollector.webp",
    emojis: ["\uD83D\uDCA7", "\uD83D\uDD0B", "⚗️", "⛽"],
    description: "You gotta spend Elixir to make Elixir! This building makes 8 Elixir over its Lifetime. Does not appear in your starting hand."
}, {
    name: "X-Bow",
    cost: "6",
    rarity: "Epic",
    type: "Building",
    release_year: 2016,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "0.3s",
    speed: "N/A",
    img: "/cards/Xbow.webp",
    emojis: ["\uD83C\uDFF9", "✖️", "\uD83C\uDFDA️"],
    description: "Nice tower you got there. Would be a shame if this X-Bow whittled it down from this side of the Arena..."
}, {
    name: "Barbarian Hut",
    cost: "6",
    rarity: "Rare",
    type: "Building",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.3s",
    speed: "Medium",
    img: "/cards/BarbarianHut.webp",
    emojis: ["\uD83C\uDFDA️", "✨", "\uD83E\uDD3A", "\uD83E\uDD3A"],
    description: "Building that periodically spawns Barbarians to fight the enemy. Time to make the Barbarians!"
}, {
    name: "Mirror",
    cost: "?",
    rarity: "Epic",
    type: "Spell",
    release_year: 2016,
    range: "N/A",
    targets: "N/A",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Mirror.webp",
    emojis: ["\uD83D\uDE4B\uD83C\uDFFB‍♂️", "\uD83D\uDD04", "⬆️", "\uD83D\uDE4B\uD83C\uDFFB‍♂️"],
    description: "Mirrors your last card played for +1 Elixir. Does not appear in your starting hand."
}, {
    name: "Rage",
    cost: "2",
    rarity: "Epic",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Rage.webp",
    emojis: ["\uD83E\uDDEA", "✨", "\uD83E\uDD2C"],
    description: "Increases troop movement and attack speed. Buildings attack faster and summon troops quicker, too. Chaaaarge!"
}, {
    name: "Zap",
    cost: "2",
    rarity: "Common",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Zap.webp",
    emojis: ["\uD83E\uDDEA", "\uD83D\uDE35", "⚡", "\uD83D\uDD35"],
    description: "Zaps enemies, briefly stunning them and dealing damage inside a small radius. Reduced damage to Crown Towers."
}, {
    name: "The Log",
    cost: "2",
    rarity: "Legendary",
    type: "Spell",
    release_year: 2016,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/TheLog.webp",
    emojis: ["\uD83D\uDD04", "\uD83D\uDCA8", "\uD83C\uDF32"],
    description: 'A spilt bottle of Rage turned an innocent tree trunk into "The Log". Now, it seeks revenge by crushing anything in its path! Reduced damage to Crown Towers.'
}, {
    name: "Barbarian Barrel",
    cost: "2",
    rarity: "Epic",
    type: "Spell",
    release_year: 2018,
    range: "Ranged",
    targets: "Ground",
    hit_speed: "1.3s",
    speed: "Medium",
    img: "/cards/BarbarianBarrel.webp",
    emojis: ["\uD83D\uDD04", "\uD83D\uDEE2️", "\uD83E\uDD3A"],
    description: "It rolls over and damages anything in its path, then breaks open and out pops a Barbarian! How did he get inside?!"
}, {
    name: "Giant Snowball",
    cost: "2",
    rarity: "Common",
    type: "Spell",
    release_year: 2018,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/GiantSnowball.webp",
    emojis: ["❄️", "\uD83E\uDD3E", "\uD83E\uDD76"],
    description: "It's HUGE! Once it began rolling down Frozen Peak, there was no stopping it. Enemies hit are knocked back and slowed down. Reduced damage to Crown Towers."
}, {
    name: "Goblin Curse",
    cost: "2",
    rarity: "Epic",
    type: "Spell",
    release_year: 2024,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/GoblinCurse.webp",
    emojis: ["\uD83E\uDDEA", "✨", "\uD83D\uDC7A", "\uD83D\uDC7A"],
    description: "And thrice were their afflictions... nixed, vexed, and hexed! Enemy troops in the area will receive extra damage from attacks and become Goblins when destroyed. Deals damage to enemies over time."
}, {
    name: "Arrows",
    cost: "3",
    rarity: "Common",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Arrows.webp",
    emojis: ["\uD83C\uDFF9", "\uD83C\uDFF9", "\uD83C\uDFF9"],
    description: "Arrows pepper a large area, damaging all enemies hit. Reduced damage to Crown Towers."
}, {
    name: "Goblin Barrel",
    cost: "3",
    rarity: "Epic",
    type: "Spell",
    release_year: 2016,
    range: "Melee",
    targets: "Ground",
    hit_speed: "1.1s",
    speed: "Very Fast",
    img: "/cards/GoblinBarrel.webp",
    emojis: ["✈️", "\uD83D\uDEE2️", "\uD83D\uDC7A", "\uD83D\uDC7A"],
    description: "Spawns three Goblins anywhere in the Arena. It's going to be a thrilling ride, boys!"
}, {
    name: "Tornado",
    cost: "3",
    rarity: "Epic",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Tornado.webp",
    emojis: ["\uD83D\uDD04", "\uD83C\uDF00", "\uD83C\uDF2A️"],
    description: "Drags enemy troops to its center while dealing damage over time, just like a magnet. A big, swirling, Tornado-y magnet."
}, {
    name: "Clone",
    cost: "3",
    rarity: "Epic",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Clone.webp",
    emojis: ["\uD83E\uDDEA", "✨", "\uD83E\uDDD1‍\uD83E\uDD1D‍\uD83E\uDDD1", "\uD83E\uDDD1‍\uD83E\uDD1D‍\uD83E\uDDD1"],
    description: "Duplicates all friendly troops in the target area. Cloned troops are fragile, but pack the same punch as the original! Doesn't affect buildings."
}, {
    name: "Earthquake",
    cost: "3",
    rarity: "Rare",
    type: "Spell",
    release_year: 2019,
    range: "Area Effect",
    targets: "Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Earthquake.webp",
    emojis: ["\uD83E\uDDEA", "⚠️", "\uD83C\uDF0D", "\uD83D\uDD73️"],
    description: "Deals Damage per second to Troops and Crown Towers. Deals huge Building Damage! Does not affect flying units (it is an EARTHquake, after all)."
}, {
    name: "Royal Delivery",
    cost: "3",
    rarity: "Common",
    type: "Spell",
    release_year: 2020,
    range: "Melee",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "Medium",
    img: "/cards/RoyalDelivery.webp",
    emojis: ["\uD83D\uDC51", "\uD83D\uDC82", "\uD83E\uDE82"],
    description: "No need to sign for this package! Dropped from the sky, it deals Area Damage to enemy Troops before delivering a Royal Recruit. The empty box is also handy for espionage."
}, {
    name: "Void",
    cost: "3",
    rarity: "Epic",
    type: "Spell",
    release_year: 2024,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Void.webp",
    emojis: ["\uD83E\uDDEA", "\uD83D\uDD73️", "☄️", "☄️"],
    description: "You shall not pass! Unless there are lot of you...Creates a field of dark magic damaging all enemy troop and buildings within. More damage is dealt when fewer targets are on its area. Reduced damage to Crown Towers."
}, {
    name: "Fireball",
    cost: "4",
    rarity: "Rare",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Fireball.webp",
    emojis: ["\uD83D\uDD25", "⚽", "\uD83D\uDCA5"],
    description: "Annnnnd... Fireball. Incinerates a small area, dealing high damage. Reduced damage to Crown Towers."
}, {
    name: "Freeze",
    cost: "4",
    rarity: "Epic",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Freeze.webp",
    emojis: ["\uD83E\uDDEA", "✨", "❄️", "\uD83E\uDD76"],
    description: "Freezes and damages enemy troops and buildings, making them unable to move or attack. Everybody chill. Reduced damage to Crown Towers."
}, {
    name: "Poison",
    cost: "4",
    rarity: "Epic",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Poison.webp",
    emojis: ["\uD83E\uDDEA", "☣️", "☠️"],
    description: "Covers the area in a deadly toxin, damaging enemy troops and buildings over time. Yet somehow leaves the grass green and healthy. Go figure! Reduced damage to Crown Towers."
}, {
    name: "Graveyard",
    cost: "5",
    rarity: "Legendary",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Ground",
    hit_speed: "N/A",
    speed: "Fast",
    img: "/cards/Graveyard.webp",
    emojis: ["⚰️", "✨", "\uD83D\uDC80", "\uD83D\uDC80"],
    description: "Surprise! It's a party. A Skeleton party, anywhere in the Arena. Yay!"
}, {
    name: "Rocket",
    cost: "6",
    rarity: "Rare",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Rocket.webp",
    emojis: ["\uD83D\uDE80", "\uD83D\uDE31", "\uD83D\uDCA5"],
    description: "Deals high damage to a small area. Looks really awesome doing it. Reduced damage to Crown Towers."
}, {
    name: "Lightning",
    cost: "6",
    rarity: "Epic",
    type: "Spell",
    release_year: 2016,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Lightning.webp",
    emojis: ["\uD83E\uDDEA", "⚡", "\uD83C\uDF29️"],
    description: "Bolts of lightning damage and stun up to three enemy troops or buildings with the most hitpoints in the target area. Reduced damage to Crown Towers."
}, {
    name: "Spirit Empress",
    cost: "6",
    rarity: "Legendary",
    type: "Troop",
    release_year: 2025,
    range: "Ranged",
    targets: "Air & Ground",
    hit_speed: "1.4s",
    speed: "Medium",
    img: "/cards/SpiritEmpress.webp",
    emojis: ["\uD83D\uDC7B", "\uD83D\uDD04", "\uD83D\uDC51", "\uD83D\uDC09"],
    description: "Behold the Spirit Empress, the First of Her Name, Protector of Spirits, Rider of Dragons. Summon her as a hard-hitting ground troop for 3 Elixir, or atop her majestic spirit dragon for 6 Elixir."
}, {
    name: "Vines",
    cost: "3",
    rarity: "Epic",
    type: "Spell",
    release_year: 2025,
    range: "Area Effect",
    targets: "Air & Ground",
    hit_speed: "N/A",
    speed: "N/A",
    img: "/cards/Vines.webp",
    emojis: ["\uD83E\uDDEA", "\uD83D\uDD17", "\uD83D\uDD12", "\uD83C\uDF3F"],
    description: "Entangle the three highest hitpoint troops or buildings in the area, stunning them while doing damage. If the troop is in the air, they'll ground them. Don't worry, they'll grow on you!"
}]